/**
 * Volcano Documentation Sidebar
 * Phase 1: Autogenerated from docs/ folder structure
 * Phase 2 will apply full sidebar from Hugo menus.toml
 */

module.exports = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};
